// js/testapps/next/src/app/page.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

'use client';

import type { tellJoke } from '@/genkit/joke';
import { runFlow, streamFlow } from '@genkit-ai/next/client';
import { useEffect, useRef, useState } from 'react';
import styles from './page.module.css';

async function run(type: string, setResponse: (response: string) => void) {
  setResponse('...');
  const resp = await runFlow<typeof tellJoke>({
    url: '/api/joke',
    input: type === '' ? null : type,
  });
  setResponse(resp);
}

async function stream(type: string, setResponse: (response: string) => void) {
  let accum = '';
  setResponse('...');
  const { stream, output } = streamFlow<typeof tellJoke>({
    url: '/api/joke',
    input: type === '' ? null : type,
  });
  for await (const chunk of stream) {
    accum = accum + chunk;
    setResponse(accum);
  }
  setResponse(await output);
}

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [response, setResponse] = useState<string>('Pick a joke type');
  function focus() {
    if (inputRef.current) {
      inputRef.current.focus();
    }
  }
  useEffect(focus);
  return (
    <>
      <div className={styles.title}>
        <input
          type="text"
          alt="Joke type"
          placeholder="Joke type"
          ref={inputRef}></input>
        <button
          onClick={() => {
            run(inputRef.current!.value, setResponse);
            focus();
          }}>
          Run
        </button>
        <button
          onClick={() => {
            stream(inputRef.current!.value, setResponse);
            focus();
          }}>
          Stream
        </button>
      </div>
      <div>{response}</div>
    </>
  );
}

// samples/js-firebase/my-app/src/app/app.component.ts
/**
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { streamFlow } from '../utils/flow';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  count: string = '3';
  url: string =
    'http://127.0.0.1:5001/YOUR-PROJECT-ID/us-central1/streamCharacters';
  characters: any = undefined;
  error?: string = undefined;
  loading: boolean = false;

  async callFlow() {
    this.characters = undefined;
    this.error = undefined;
    this.loading = true;
    try {
      const response = streamFlow({
        url: this.url,
        payload: parseInt(this.count),
      });
      for await (const chunk of response.stream()) {
        this.characters = chunk;
      }
      console.log('streamConsumer done', await response.output());
      this.loading = false;
    } catch (e) {
      this.loading = false;
      if ((e as any).cause) {
        this.error = `${(e as any).cause}`;
      } else {
        this.error = `${e}`;
      }
    }
  }
}

<!--
 Copyright 2024 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<h1>RPG Character Generator</h1>
Generator URL:
<input type="text" [(ngModel)]="url" style="width: 500px" /><br /><br />
How many chatacters do you need? <input type="text" [(ngModel)]="count" />
<button (click)="callFlow()">Generate</button>

<div *ngIf="loading">Loading...</div>
<div *ngIf="error">
  {{ error }}
</div>
<div *ngIf="characters">
  <div *ngFor="let character of characters.characters">
    <b>{{ character.name }}</b>
    <ul>
      <li *ngFor="let ability of character.abilities">{{ ability }}</li>
    </ul>
  </div>
</div>
